

as filename:
    #!/usr/bin/env sh
    cd "{{invocation_directory()}}"
    riscv64-none-elf-as -o {{filename}}.o {{filename}}.s

ld filename:
    #!/usr/bin/env sh
    cd "{{invocation_directory()}}"
    riscv64-none-elf-ld -o {{filename}}.out {{filename}}.o

run filename:
    #!/usr/bin/env sh
    cd "{{invocation_directory()}}"
    qemu-riscv64 {{filename}}.out

go filename:
    #!/usr/bin/env sh
    cd "{{invocation_directory()}}"
    just as "{{filename}}"
    just ld "{{filename}}"
    just run "{{filename}}"
